config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('game.urls')),
    path('accounts/', include('allauth.urls')),
]

game/urls.py
from django.urls import path
from . import views

app_name = 'game'

urlpatterns = [
    path('create/', views.create_game, name='create_game'),  # 게임 생성 (공격)
    path('attackSave/', views.attackSave, name='attackSave'),  # 게임 생성 (공격)
    path('list/<int:user_id>/', views.game_list, name='game_list'),  # 게임 리스트 보기
    path('cancel/<int:game_id>/', views.cancel_game, name='cancel_game'),
    path('gameInfo1/<int:game_id>/', views.gameInfo1, name='gameInfo1'), #게임 진행중일때 정보
    path('gameInfo2/<int:game_id>/', views.gameInfo2 ,name='gameInfo2'), # 카운터 어텍 상황일때 정보
    path('gameInfo3/<int:game_id>/', views.gameInfo3, name='gameInfo3'), # 게임 결과가 나왔을때 정보
    path('respond/<int:game_id>/', views.respond_game, name='respond_game'),  # 게임에 반격
    path('respondSave/<int:game_id>', views.respondSave, name='respondSave'),
    path('rankings/', views.rankings, name='rankings'),  # 랭킹 보기
]

templates/smk_gameStart/smk_Attack.html
{% extends '../base/base.html'%}
{% load static%}
{% block head %}
  <link rel="stylesheet" href="{%static 'game/smk.css'%}">
{% endblock head %}
{% block content %}
    <section class="game-box">
      <form method="POST" action="{%url 'game:attackSave' %}">

        {% csrf_token %}      

        <div class="gameAttack-defender">
          <h2>내가 고른 카드: </h2>
          <div id="cardForm">
            <div id="radioButtons">
              {% for number in random_numbers %}
                <div class="radio-item">
                  <input type="radio" name="card" value="{{ number }}" id="card{{ number }}">
                  <label for="card{{ number }}">{{ number }}</label>
                </div>
              {% endfor %}
            </div>
          </div>
        </div>
        
      <div class="gameAttack-container">
        <h2> Defender: </h2>
        <select id = "defender-select" name = "defender">
          {% for defender in defenders %}
            <option value="{{ defender.id }}">{{ defender.username }}</option>
          {% endfor %}
        </select>
      </div>


      <div class="button-container">
        <button type="submit" class="game-button" style="color:#319B88">Attack!</button>
      </div>
    </section>

    </form>
    <!-- 구현 -->
{% endblock content%}

templates/smk_gameStart/smk_CounterAttack.html
{% extends '../base/base.html'%}
{% load static%}
{% block head %}
  <link rel="stylesheet" href="{%static 'game/smk.css'%}">
{% endblock head %}
{% block content %}
    <form method="POST" action="{%url 'game:respondSave' game.id%}">
      {% csrf_token %}      

    <section class="game-box">
      <div class="gameAttack-defender">
        <h2>반격할 카드: </h2>
          <div id="radioButtons">
            {% for number in random_numbers %}
              <div class="radio-item">
                <input type="radio" name="card" value="{{ number }}" id="card{{ number }}">
                <label for="card{{ number }}">{{ number }}</label>
              </div>
            {% endfor %}
          </div>
      </div>

      <div class="button-container">
        <button type="submit" class="game-button" style="color:#319B88">Attack!</button>
      </div>
    </section>
    
    </form>
{% endblock content%}