config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('game.urls')),
    path('accounts/', include('allauth.urls')),
]

game/urls.py
from django.urls import path
from . import views

app_name = 'game'

urlpatterns = [
    path('create/', views.create_game, name='create_game'),  # 게임 생성 (공격)
    path('attackSave/', views.attackSave, name='attackSave'),  # 게임 생성 (공격)
    path('list/<int:user_id>/', views.game_list, name='game_list'),  # 게임 리스트 보기
    path('cancel/<int:game_id>/', views.cancel_game, name='cancel_game'),
    path('gameInfo1/<int:game_id>/', views.gameInfo1, name='gameInfo1'), #게임 진행중일때 정보
    path('gameInfo2/<int:game_id>/', views.gameInfo2 ,name='gameInfo2'), # 카운터 어텍 상황일때 정보
    path('gameInfo3/<int:game_id>/', views.gameInfo3, name='gameInfo3'), # 게임 결과가 나왔을때 정보
    path('respond/<int:game_id>/', views.respond_game, name='respond_game'),  # 게임에 반격
    path('respondSave/<int:game_id>', views.respondSave, name='respondSave'),
    path('rankings/', views.rankings, name='rankings'),  # 랭킹 보기
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.main, name='main'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

templates/base/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Piro22_CardGame_3</title>
    <link rel="stylesheet" href="{% static 'game/reset.css'%}" />
    <link rel="stylesheet" href="{% static 'game/base.css'%}" />
    {% block head %} {% endblock %}
  </head>
  <body>
    <header>
      <nav>
        <a href="{%url 'users:main' %}">Pirogrammer Card Game</a>
        <div class="base_menus">
          {% block base_menus%}
          {% if user.is_authenticated %}
          <span>{{ user.username }} 님</span>
          <a href="{%url 'game:create_game' %} ">게임하기</a>
          <a href="{% url 'game:rankings' %}">랭킹보기</a>
          <a href="{% url 'users:logout' %}">로그아웃</a>
          {% endif %}
          {%endblock base_menus%}
        </div>
      </nav>
    </header>
    <main>{% block content %} {% endblock %}</main>
    <footer>
      <p>피로그래밍 22기 카드게임 세션3조</p>
    </footer>
  </body>
  {% block js%} {% endblock js%}
</html>