config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('game.urls')),
    path('accounts/', include('allauth.urls')),
]

game/urls.py
from django.urls import path
from . import views

app_name = 'game'

urlpatterns = [
    path('create/', views.create_game, name='create_game'),  # 게임 생성 (공격)
    path('attackSave/', views.attackSave, name='attackSave'),  # 게임 생성 (공격)
    path('list/<int:user_id>/', views.game_list, name='game_list'),  # 게임 리스트 보기
    path('cancel/<int:game_id>/', views.cancel_game, name='cancel_game'),
    path('gameInfo1/<int:game_id>/', views.gameInfo1, name='gameInfo1'), #게임 진행중일때 정보
    path('gameInfo2/<int:game_id>/', views.gameInfo2 ,name='gameInfo2'), # 카운터 어텍 상황일때 정보
    path('gameInfo3/<int:game_id>/', views.gameInfo3, name='gameInfo3'), # 게임 결과가 나왔을때 정보
    path('respond/<int:game_id>/', views.respond_game, name='respond_game'),  # 게임에 반격
    path('respondSave/<int:game_id>', views.respondSave, name='respondSave'),
    path('rankings/', views.rankings, name='rankings'),  # 랭킹 보기
]

game/models.py
from django.db import models
from users.models import CustomUser

class Game(models.Model):
    attacker = models.ForeignKey(
        CustomUser,
        related_name='games_as_attacker',
        on_delete=models.CASCADE
    )
    defender = models.ForeignKey(
        CustomUser,
        related_name='games_as_defender',
        on_delete=models.CASCADE
    )
    attacker_card = models.IntegerField()
    defender_card = models.IntegerField(null=True, blank=True)
    result = models.CharField(max_length=10, null=True, blank=True)
    winner = models.ForeignKey(
        CustomUser,
        related_name='games_as_winner',
        null=True, blank=True,
        on_delete=models.SET_NULL
    )
    is_greater_wins = models.BooleanField()

game/views.py
from django.shortcuts import render, redirect, get_object_or_404
from users.models import CustomUser
import random
from .models import Game
from django.db.models import Q
# Create your views here.

def gameInfo1(request, game_id):
    game = get_object_or_404(Game, id=game_id)  # game_id로 게임 객체를 가져옴
    context = {
        'game': game,
        'attacker': game.attacker.username,
        'defender': game.defender.username,
    }
    return render(request, 'gameInfo/gameInfo1.html', context)

def gameInfo2(request, game_id):
    game = get_object_or_404(Game, id=game_id)
    context = {
        'game': game,
        'attacker': game.attacker.username,
        'defender': game.defender.username,
    }  # game_id로 게임 객체를 가져옴
    return render(request, 'gameInfo/gameInfo2.html', context)

def gameInfo3(request, game_id):
    game = get_object_or_404(Game, id=game_id)

    # 결과 처리
    result = game_result(game.attacker_card, game.defender_card, game.is_greater_wins)

    # 점수 계산
    # winner_score = game.attacker_card
    # loser_score = game.defender_card
    context = {
        'game': game,
        'attacker': game.attacker,
        'defender': game.defender,
        'attacker_card': game.attacker_card,
        'defender_card': game.defender_card,
        'loser_score':  - game.defender_card,
        'result': result,
        'winner': game.winner,
    }
    return render(request, 'gameInfo/gameInfo3.html', context)


def create_game(request):
    defenders = CustomUser.objects.exclude(id=request.user.id)
    random_numbers = random.sample(range(1, 11), 5)  # 랜덤 숫자 생성

    return render(request, 'smk_gameStart/smk_Attack.html', {
        'defenders': defenders,
        'random_numbers': random_numbers,
    })

def attackSave(request):
    if request.method == 'POST':
        defender_id = request.POST.get('defender')
        defender = CustomUser.objects.get(id=defender_id)
        attacker = request.user
        selected_card = request.POST.get('card')
        is_greater_wins = random.choice([True, False])
        
        
        if defender and attacker and selected_card:
            new_game = Game(attacker=attacker, defender=defender, attacker_card=selected_card, is_greater_wins=is_greater_wins)
            game = new_game.save()
            return redirect('game:game_list', attacker.id)

def game_list(request, user_id):
    user = CustomUser.objects.get(id=user_id)
    games = Game.objects.filter(Q(attacker=user) | Q(defender=user))
    context = {
        'user': user,
        'games': games,
    }
    return render(request, 'game/cms.html', context)

def rankings(request):
    users = CustomUser.objects.order_by('-score')[:3]
    context = {
        'users':users,
    }
    return render(request, 'game/rank.html', context)

def respond_game(request, game_id):
    game = get_object_or_404(Game, id=game_id) # 1. game_id로 특정 게임 객체 가져오기
    random_numbers = random.sample(range(1, 11), 5) # 2. 랜덤 숫자 생성 (1~10 중 5개)
    return render(request, 'smk_gameStart/smk_CounterAttack.html', {  # 3. 템플릿에 데이터 전달
        'game': game,  # 게임 객체
        'random_numbers': random_numbers,  # 랜덤 숫자
    })

def cancel_game(request, game_id):
    game = Game.objects.get(id=game_id)
    if game.attacker.username == request.user.username:
        game.delete()
    return redirect('game:game_list', request.user.id)

def respondSave(request, game_id):
    if request.method == 'POST':
        game = Game.objects.get(id=game_id)
        if game.defender == request.user:
            game.defender_card = int(request.POST.get('card'))
            game.save()
            attacker = CustomUser.objects.get(id=game.attacker.id)
            defender = CustomUser.objects.get(id=game.defender.id)
            result = game_result(game.attacker_card, game.defender_card, game.is_greater_wins)
            if result == 0:
                game.winner = None
            elif result == 1:
                game.winner = attacker
                attacker.score += game.attacker_card
                defender.score -= game.defender_card
            else:
                game.winner = defender
                defender.score += game.defender_card
                attacker.score -= game.attacker_card
            attacker.save()
            defender.save()
            game.save()
            return redirect('game:game_list', defender.id)
            

def game_result(user1_card, user2_card, is_greater_wins):
    if user1_card == user2_card:
        return 0 #무승부
    if is_greater_wins:
        return 1 if user1_card > user2_card else 2 #1: user1 승, 2: user2 승
    return 1 if user1_card < user2_card else 2
            

templates/game/cms.html
{% extends '../base/base.html'%}
{% load static%}
{% block head %}
  <link rel="stylesheet" href="{%static 'game/cms.css'%}">
{% endblock head %}
{% block content %}
    <div id="cms-main-container">
      <div>
        <h2 id="History-list">History List</h2>
      </div>
      <div id="now-player">
        <p>현재 플레이어 <span> : {{user.username}}</span></p>
      </div>
      <div id="game-list">
        <table>
          <thead class="gameTbHeader">
            <tr>
              <th>게임번호</th>
              <th>플레이어</th>
              <th>게임상황</th>
              <th>게임정보</th>
            </tr>
          </thead>
          <tbody>
            {% for game in games%}
            <tr class="gameTbList">
              <td>{{game.id}}</td>
              <td>{{game.attacker}} vs {{game.defender}}</td>
              <td>
                {% if game.winner == None and not game.defender_card%}
                  {%if game.attacker.username == user.username%} {% comment %}로그인한 유저가 공격하고 게임 안끝났을 때{% endcomment %}
                    <span class="gameProgress">
                      진행중...<a href="{%url 'game:cancel_game' game.id%}">개임취소</a>
                    </span>
            
                  {% else %}
                    <span class="counterAttack">
                      <a href="{%url 'game:respond_game' game.id%}">CounterAttack</a>
                    </span>
                  {% endif %}
                {% else %}
                  <span class="">
                    결과: 
                    {% if game.winner.username == user.username %}
                      승리
                    {% elif game.winner.username == None %}
                      무승부
                    {% else %}
                      패배
                    {% endif %}
                  </span>
                {% endif %}
              </td>
              <td>
                <a href="
                  {% if game.winner == None and not game.defender_card%}
                    {% if game.attacker.username == user.username %} 
                      {% url 'game:gameInfo1' game.id %}
                    {% else %} 
                      {% url 'game:gameInfo2' game.id %}
                    {% endif %}
                  {% else %}
                    {% url 'game:gameInfo3' game.id %}
                  {% endif %}
                ">
                  <button class="gameTbBtn">게임 정보</button>
                </a>
              </td>
            </tr>
            {% endfor %}
            
        </table>
      </div>
    </div>
{% endblock content%}

templates/game/jwj.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="reset.css">
    <link rel="stylesheet" href="base.css">
    <!-- {% block head %} -->
    <link rel="stylesheet" href="jwj.css">
    <!-- {% endblock %} -->
</head>
<body>
    <header>
        <nav>
          <a href="">Pirogrammer Card Game</a>
          <div class="base_menus">
            <a href="">게임하기</a>
            <a href="">랭킹보기</a>
            <a href="">로그아웃</a>
          </div>
        </nav>
    </header>
    <!-- {% block content %} -->
    <main>
        <div class="rank_container">
            <h4 class="rank_title">Piro 명예의 전당</h4>
            <div class="ranking">
                <div class="first">
                    <p>user2</p>
                    <p>11</p>
                    <div class="bar" id="bar1">1</div>
                </div>
                <div class="second">
                    <p>user1</p>
                    <p>-1</p>
                    <div class="bar" id="bar2">2</div>
                </div>
                <div class="third">
                    <p>user4</p>
                    <p>-6</p>
                    <div class="bar" id="bar3">3</div>
                </div>
            </div>
            <a href="">
                <button class="list_button">전적 목록</button>
            </a>
        </div>
    </main>
    <!-- {% endblock %} -->
    <footer>
        <p>피로그래밍 22기 카드게임 세션3조</p>
    </footer>
</body>
</html>

templates/game/rank.html
{% extends 'base/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% block head %}
    <link rel="stylesheet" href="{% static 'game/rank.css' %}">
    <style>
        main {
          padding-top: 60px;
          padding-bottom: 40px;
          display: flex;
          align-items: center;
        }
    </style>
    {% endblock %}
</head>
<body>
    {% block content %}
        <div class="rank_container">
            <h4 class="rank_title">Piro 명예의 전당</h4>
            <div class="ranking">
                <div class="first">
                    {% if users.0 %}
                        <p>🥇{{ users.0.username }}🥇</p>
                        <p>{{ users.0.score }}</p>
                    {% else %}
                        <p>No Data</p>
                    {% endif %}
                    <div class="bar" id="bar1">1</div>
                </div>
                <div class="second">
                    {% if users.1 %}
                        <p>🥈{{ users.1.username }}🥈</p>
                        <p>{{ users.1.score }}</p>
                    {% else %}
                        <p>No Data</p>
                    {% endif %}
                    <div class="bar" id="bar2">2</div>
                </div>
                <div class="third">
                    {% if users.2 %}
                        <p>🥉{{ users.2.username }}🥉</p>
                        <p>{{ users.2.score }}</p>
                    {% else %}
                        <p>No Data</p>
                    {% endif %}
                    <div class="bar" id="bar3">3</div>
                </div>
            </div>
            <a href="{%url 'game:game_list' user.id%}">
                <button class="list_button">전적 목록</button>
            </a>
        </div>
    {% endblock %}
</body>
</html>