config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('game.urls')),
    path('accounts/', include('allauth.urls')),
]

game/urls.py
from django.urls import path
from . import views

app_name = 'game'

urlpatterns = [
    path('create/', views.create_game, name='create_game'),  # 게임 생성 (공격)
    path('attackSave/', views.attackSave, name='attackSave'),  # 게임 생성 (공격)
    path('list/<int:user_id>/', views.game_list, name='game_list'),  # 게임 리스트 보기
    path('cancel/<int:game_id>/', views.cancel_game, name='cancel_game'),
    path('gameInfo1/<int:game_id>/', views.gameInfo1, name='gameInfo1'), #게임 진행중일때 정보
    path('gameInfo2/<int:game_id>/', views.gameInfo2 ,name='gameInfo2'), # 카운터 어텍 상황일때 정보
    path('gameInfo3/<int:game_id>/', views.gameInfo3, name='gameInfo3'), # 게임 결과가 나왔을때 정보
    path('respond/<int:game_id>/', views.respond_game, name='respond_game'),  # 게임에 반격
    path('respondSave/<int:game_id>', views.respondSave, name='respondSave'),
    path('rankings/', views.rankings, name='rankings'),  # 랭킹 보기
]

templates/gameInfo/gameInfo1.html
{% extends '../base/base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'game/gameInfo.css' %}">
{% endblock head %}
{% block content %}
<section class="game-box">
  <h2>{{ game.id }} - {{ attacker }} VS {{ defender }}</h2>
  <p>진행중...</p>
  <ul class="game-stats">
    <li><strong>나:</strong> {{ game.attacker_card }}</li>
    
  </ul>
  <div class="game-actions">
    <a href="{% url 'game:cancel_game' game.id %}">
      <button>게임취소</button>
    </a>
    <a href="{% url 'game:game_list' request.user.id %}">
      <button>전적목록</button>
    </a>
  </div>
</section>
{% endblock content %}

templates/gameInfo/gameInfo2.html
{% extends '../base/base.html'%} {% load static%} {% block head %}
<link rel="stylesheet" href="{%static 'game/gameInfo.css'%}" />
</style>
{% endblock head %} {% block content %}
<!-- 구현 -->
<section class="game-box">
  <h2>{{ game.id }} - {{ attacker }} VS {{ defender }}</h2>
  <div class="game-actions">
    <a href="{% url 'game:respond_game' game.id %}">
      <button>반격하기</button>
    </a>
    <button>전적목록</button>
    </a>
  </div>
</section>
<!-- 구현 -->
{% endblock content%}

templates/gameInfo/gameInfo3.html
{% extends '../base/base.html'%}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'game/gameInfo.css' %}" />
{% endblock head %}
{% block content %}
<!-- 구현 -->
<section class="game-box">
  <h2>{{ game.id }} - {{ attacker }} VS {{ defender }}</h2>
  <p>
    {% if game.is_greater_wins %}
      숫자가 큰 사람이 이깁니다.
    {% else %}
      숫자가 작은 사람이 이깁니다.
    {% endif %}
  </p>
  <ul class="game-stats">
    <li>{{ attacker.username }}: {{ attacker_card }}</li>
    <li>{{ defender.username }}: 
      {% if defender_card %}
        {{ defender_card }}
      {% else %}
        아직 선택하지 않음
      {% endif %}
    </li>
    <li>결과: 
      {% if result == 0 %}
        무승부
      {% elif request.user == attacker %}
        {% if result == 1 %}
          승리
        {% else %}
          패배
        {% endif %}
      {% elif request.user == defender %}
        {% if result == 2 %}
          승리
        {% else %}
          패배
        {% endif %}
      {% endif %}
    </li>
    <li>
      점수: 
      {% if result == 0 %}
        0
      {% elif request.user == attacker %}
        {% if result == 1 %}
          {{ attacker_card }}
        {% else %}
          -{{ attacker_card }}
        {% endif %}
      {% elif request.user == defender %}
        {% if result == 2 %}
          {{ defender_card }}
        {% else %}
          -{{ defender_card }}
        {% endif %}
      {% endif %}
    </li>
</ul>
  <div class="game-actions">
    <a href="{% url 'game:game_list' request.user.id %}">
      <button>전적목록</button>
    </a>
  </div>
</section>
<!-- 구현 -->
{% endblock content %}